#!/usr/bin/env python3
"""
WOLFSTRIKE Setup Script
Author: ATHEX BLACK HAT
Team: Wolf Intelligence PK
Version: 1.0.0

Installation script for WOLFSTRIKE - Ultimate Web Penetration Testing Toolkit.
"""

import setuptools
from pathlib import Path

this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text(encoding='utf-8')

setuptools.setup(
    name="wolfstrike",
    version="1.0.0",
    codename="Shadowfang",
    author="ATHEX BLACK HAT",
    author_email="wolfintelligencepk@protonmail.com",
    description="Ultimate All-in-One Web Penetration Testing Toolkit",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Athexblackhat/WolfStrike",
    project_urls={
        "Bug Tracker": "https://github.com/Athexblackhat/WolfStrike/issues",
        "Documentation": "https://github.com/Athexblackhat/WolfStrike/wiki",
        "Source Code": "https://github.com/Athexblackhat/WolfStrike",
    },
    packages=setuptools.find_packages(
        include=[
            'core', 'core.*',
            'cli', 'cli.*',
            'modules', 'modules.*',
            'modules/recon', 'modules/recon.*',
            'modules/scanner', 'modules/scanner.*',
            'modules/vuln_scanner', 'modules/vuln_scanner.*',
            'modules/attacks', 'modules/attacks.*',
            'modules/auth_tester', 'modules/auth_tester.*',
            'modules/crawler', 'modules/crawler.*',
            'modules/api_tester', 'modules/api_tester.*',
            'modules/network', 'modules/network.*',
            'modules/osint', 'modules/osint.*',
            'modules/reporting', 'modules/reporting.*',
            'ai_engine', 'ai_engine.*',
            'stealth', 'stealth.*',
            'utils', 'utils.*',
            'integrations', 'integrations.*',
            'database', 'database.*',
            'termux', 'termux.*',
        ],
        exclude=["tests", "tests.*", "debug_tool", "generate_files"],
    ),
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Information Technology",
        "Intended Audience :: System Administrators",
        "Intended Audience :: Developers",
        "Topic :: Security",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Software Development :: Testing",
        "Topic :: System :: Networking :: Monitoring",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
        "Operating System :: POSIX :: Linux",
        "Operating System :: Microsoft :: Windows",
        "Operating System :: MacOS",
        "Operating System :: Android",
        "Environment :: Console",
        "Natural Language :: English",
    ],
    python_requires=">=3.10",
    install_requires=[
        "requests>=2.31.0",
        "urllib3>=2.1.0",
        "certifi>=2024.0.0",
        "pyyaml>=6.0.0",
        "beautifulsoup4>=4.12.0",
        "dnspython>=2.6.0",
        "sqlalchemy>=2.0.0",
        "fpdf2>=2.7.0",
        "rich>=13.7.0",
        "colorama>=0.4.6",
        "tqdm>=4.66.0",
        "python-dateutil>=2.8.0",
        "cryptography>=42.0.0",
        "pyjwt>=2.8.0",
        "shodan>=1.30.0",
        "selenium>=4.16.0",
        "pillow>=10.2.0",
        "aiohttp>=3.9.0",
        "aiodns>=3.1.0",
        "psutil>=5.9.0",
    ],
    extras_require={
        "dev": [
            "pytest>=8.0.0",
            "pytest-cov>=4.0.0",
            "black>=24.0.0",
            "flake8>=7.0.0",
            "pylint>=3.0.0",
            "mypy>=1.8.0",
            "isort>=5.13.0",
            "bandit>=1.7.0",
            "safety>=2.3.0",
        ],
        "full": [
            "nmap>=0.0.1",
            "python-nmap>=0.7.0",
            "whois>=0.9.0",
            "censys>=2.2.0",
            "securitytrails>=0.1.0",
            "pdfkit>=1.0.0",
            "selenium>=4.16.0",
            "playwright>=1.40.0",
            "mitmproxy>=10.0.0",
        ],
        "termux": [
            "requests>=2.31.0",
            "beautifulsoup4>=4.12.0",
            "certifi>=2024.0.0",
            "pyyaml>=6.0.0",
            "colorama>=0.4.6",
            "tqdm>=4.66.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "wolfstrike=wolfstrike:main",
            "wolfstrike-debug=debug_tool:main",
            "wolfstrike-setup=generate_files:main",
        ],
    },
    include_package_data=True,
    package_data={
        "wolfstrike": [
            "wordlists/*.txt",
            "wordlists/*.json",
            "config/*.yaml",
            "config/*.json",
            "installers/*.sh",
            "installers/*.bat",
            "database/migrations/*.py",
        ],
    },
    exclude_package_data={
        "": ["__pycache__", "*.pyc", "*.pyo", ".git", ".venv", "venv"],
    },
    zip_safe=False,
    platforms=["linux", "win32", "darwin", "android"],
    license="MIT",
    keywords=[
        "security",
        "pentest",
        "penetration-testing",
        "vulnerability-scanner",
        "web-security",
        "hacking",
        "exploit",
        "reconnaissance",
        "osint",
        "network-scanner",
        "port-scanner",
        "xss",
        "sql-injection",
        "csrf",
        "ssrf",
        "ssti",
        "lfi",
        "rfi",
        "api-security",
        "authentication",
        "brute-force",
        "crawler",
        "spider",
        "fuzzer",
        "payload",
        "wordlist",
        "reporting",
        "mitre-attack",
        "cvss",
        "risk-assessment",
        "wolfstrike",
        "shadowfang",
        "wolf-intelligence",
        "athex-black-hat",
    ],
)