# modules/recon/waf_detect.py

"""
WAF Detection Module
Author: ATHEX BLACK HAT
Team: Wolf Intelligence PK
Version: 1.0.0

Detects Web Application Firewalls protecting the target
and identifies potential bypass techniques.
"""

from typing import Dict, List, Any, Optional, Tuple

import requests
from requests.exceptions import RequestException


class WAFDetector:
    """
    Web Application Firewall detector.
    
    Identifies WAF presence by analyzing response headers,
    cookies, and behavior patterns with test payloads.
    """
    
    WAF_SIGNATURES = {
        'Cloudflare': {
            'headers': ['cf-ray', 'CF-Cache-Status', '__cfduid'],
            'cookies': ['__cfduid', 'cf_clearance', '__cf_bm'],
            'response_patterns': ['Cloudflare Ray ID:', 'Attention Required! | Cloudflare'],
        },
        'AWS WAF': {
            'headers': ['x-amzn-RequestId', 'x-amz-cf-id'],
            'cookies': ['aws-waf-token'],
            'response_patterns': ['Request blocked.', 'AWS WAF'],
        },
        'Akamai': {
            'headers': ['X-Akamai-Transformed', 'Akamai-Ghost'],
            'cookies': ['ak_bmsc', 'bm_sz'],
            'response_patterns': ['Reference #', 'Access Denied'],
        },
        'Imperva': {
            'headers': ['X-Iinfo'],
            'cookies': ['incap_ses_', 'visid_incap_'],
            'response_patterns': ['Incapsula incident ID:', 'Request unsuccessful.'],
        },
        'F5 BIG-IP': {
            'headers': ['X-WA-Info'],
            'cookies': ['BIGipServer', 'F5_ST', 'LastMRH_Session'],
            'response_patterns': ['The requested URL was rejected.'],
        },
        'ModSecurity': {
            'headers': [],
            'cookies': [],
            'response_patterns': ['ModSecurity', 'This error was generated by Mod_Security'],
        },
        'Sucuri': {
            'headers': ['X-Sucuri-ID', 'X-Sucuri-Cache'],
            'cookies': ['sucuri_cloudproxy_uuid_'],
            'response_patterns': ['Sucuri WebSite Firewall', 'Access Denied - Sucuri'],
        },
        'Fortinet': {
            'headers': ['FORTIWAFSID'],
            'cookies': ['FORTIWAFSID'],
            'response_patterns': ['FortiWeb', 'Application Firewall'],
        },
        'Barracuda': {
            'headers': ['BarraCounterSession'],
            'cookies': ['BarraCounterSession', 'BNI__BARRACUDA'],
            'response_patterns': ['Barracuda Networks', 'Barracuda Web Application Firewall'],
        },
        'Citrix NetScaler': {
            'headers': ['X-Citrix-Via', 'NSC_'],
            'cookies': ['NSC_', 'citrix_ns_id'],
            'response_patterns': ['Citrix', 'NetScaler'],
        },
    }
    
    WAF_TEST_PAYLOADS = [
        "' OR '1'='1",
        "../../etc/passwd",
        "<script>alert(1)</script>",
        "UNION SELECT",
        "1; DROP TABLE users",
    ]
    
    def __init__(
        self,
        target: str,
        config: Optional[Dict[str, Any]] = None
    ):
        """
        Initialize the WAF detector.
        
        Args:
            target: Target URL
            config: Configuration dictionary
        """
        self.target = target.rstrip('/')
        self.config = config or {}
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        })
        
        self.timeout = self.config.get('timeout', 15)
        self.verify_ssl = self.config.get('verify_ssl', False)
        
        self.detected_wafs: List[str] = []
        self.errors: List[str] = []
    
    def fetch_baseline(self) -> Tuple[Optional[Dict[str, str]], Optional[str], Optional[Dict[str, str]]]:
        """
        Fetch baseline response for comparison.
        
        Returns:
            Tuple of (headers, text, cookies)
        """
        try:
            response = self.session.get(
                self.target,
                timeout=self.timeout,
                verify=self.verify_ssl
            )
            
            headers = dict(response.headers)
            text = response.text
            
            cookies = {}
            for cookie in response.cookies:
                cookies[cookie.name] = cookie.value
            
            return headers, text, cookies
            
        except RequestException as e:
            self.errors.append(f"Baseline fetch failed: {str(e)}")
            return None, None, None
    
    def test_payload(self, payload: str) -> Optional[requests.Response]:
        """
        Send a test payload to check WAF response.
        
        Args:
            payload: Test payload string
            
        Returns:
            HTTP response or None
        """
        try:
            params = {'test': payload, 'q': payload, 'search': payload}
            response = self.session.get(
                self.target,
                params=params,
                timeout=self.timeout,
                verify=self.verify_ssl
            )
            return response
            
        except RequestException:
            return None
    
    def detect_from_signatures(
        self,
        headers: Dict[str, str],
        text: str,
        cookies: Dict[str, str]
    ) -> List[str]:
        """
        Detect WAF from response signatures.
        
        Args:
            headers: Response headers
            text: Response text
            cookies: Response cookies
            
        Returns:
            List of detected WAF names
        """
        detected = []
        
        for waf_name, signatures in self.WAF_SIGNATURES.items():
            is_detected = False
            
            for header in signatures.get('headers', []):
                if header.lower() in [h.lower() for h in headers]:
                    is_detected = True
                    break
            
            if not is_detected:
                for cookie in signatures.get('cookies', []):
                    if cookie.lower() in [c.lower() for c in cookies]:
                        is_detected = True
                        break
            
            if not is_detected:
                for pattern in signatures.get('response_patterns', []):
                    if pattern.lower() in text.lower():
                        is_detected = True
                        break
            
            if is_detected:
                detected.append(waf_name)
        
        return detected
    
    def detect_from_behavior(self) -> List[str]:
        """
        Detect WAF from behavioral analysis with payloads.
        
        Returns:
            List of detected WAF names
        """
        for payload in self.WAF_TEST_PAYLOADS:
            response = self.test_payload(payload)
            
            if response:
                if response.status_code in [403, 406, 501]:
                    headers = dict(response.headers)
                    text = response.text
                    cookies = {c.name: c.value for c in response.cookies}
                    
                    behavioral_wafs = self.detect_from_signatures(headers, text, cookies)
                    
                    if behavioral_wafs:
                        return behavioral_wafs
        
        return []
    
    def run(self) -> Dict[str, Any]:
        """
        Run WAF detection.
        
        Returns:
            Dictionary with detection results
        """
        headers, text, cookies = self.fetch_baseline()
        
        if not text:
            return {
                'findings': [],
                'errors': self.errors,
                'waf_detected': [],
            }
        
        signature_wafs = self.detect_from_signatures(headers, text, cookies)
        behavioral_wafs = self.detect_from_behavior()
        
        all_wafs = list(set(signature_wafs + behavioral_wafs))
        
        findings = []
        
        if all_wafs:
            findings.append({
                'type': 'WAF Detected',
                'severity': 'info',
                'target': self.target,
                'description': f'Web Application Firewall detected: {", ".join(all_wafs)}',
                'evidence': {
                    'detected_wafs': all_wafs,
                    'detection_method': 'signature' if signature_wafs else 'behavioral',
                },
                'remediation': 'Review WAF configuration. Consider WAF bypass testing.',
            })
        else:
            findings.append({
                'type': 'No WAF Detected',
                'severity': 'info',
                'target': self.target,
                'description': 'No Web Application Firewall detected',
                'remediation': 'Consider implementing a WAF for additional protection',
            })
        
        return {
            'findings': findings,
            'errors': self.errors,
            'target': self.target,
            'waf_detected': all_wafs,
            'has_waf': len(all_wafs) > 0,
        }