# modules/recon/waf_detect.py

"""
WAF Detection Module
Author: ATHEX BLACK HAT
Team: Wolf Intelligence PK
Version: 1.0.0

Detects Web Application Firewalls protecting the target
and identifies potential bypass techniques.
"""

from typing import Dict, List, Any, Optional, Tuple

import requests
from requests.exceptions import RequestException, Timeout, ConnectionError


class WAFDetector:
    """
    Web Application Firewall detector.
    
    Identifies WAF presence by analyzing response headers,
    cookies, and behavior patterns with test payloads.
    """
    
    WAF_SIGNATURES = {
        'Cloudflare': {
            'headers': ['cf-ray', 'CF-Cache-Status', '__cfduid'],
            'cookies': ['__cfduid', 'cf_clearance', '__cf_bm'],
            'response_patterns': ['Cloudflare Ray ID:', 'Attention Required! | Cloudflare'],
        },
        'AWS WAF': {
            'headers': ['x-amzn-RequestId', 'x-amz-cf-id'],
            'cookies': ['aws-waf-token'],
            'response_patterns': ['Request blocked.', 'AWS WAF'],
        },
        'Akamai': {
            'headers': ['X-Akamai-Transformed', 'Akamai-Ghost'],
            'cookies': ['ak_bmsc', 'bm_sz'],
            'response_patterns': ['Reference #', 'Access Denied'],
        },
        'Imperva': {
            'headers': ['X-Iinfo'],
            'cookies': ['incap_ses_', 'visid_incap_'],
            'response_patterns': ['Incapsula incident ID:', 'Request unsuccessful.'],
        },
        'F5 BIG-IP': {
            'headers': ['X-WA-Info'],
            'cookies': ['BIGipServer', 'F5_ST', 'LastMRH_Session'],
            'response_patterns': ['The requested URL was rejected.'],
        },
        'ModSecurity': {
            'headers': [],
            'cookies': [],
            'response_patterns': ['ModSecurity', 'This error was generated by Mod_Security'],
        },
        'Sucuri': {
            'headers': ['X-Sucuri-ID', 'X-Sucuri-Cache'],
            'cookies': ['sucuri_cloudproxy_uuid_'],
            'response_patterns': ['Sucuri WebSite Firewall', 'Access Denied - Sucuri'],
        },
        'Fortinet': {
            'headers': ['FORTIWAFSID'],
            'cookies': ['FORTIWAFSID'],
            'response_patterns': ['FortiWeb', 'Application Firewall'],
        },
        'Barracuda': {
            'headers': ['BarraCounterSession'],
            'cookies': ['BarraCounterSession', 'BNI__BARRACUDA'],
            'response_patterns': ['Barracuda Networks', 'Barracuda Web Application Firewall'],
        },
        'Citrix NetScaler': {
            'headers': ['X-Citrix-Via', 'NSC_'],
            'cookies': ['NSC_', 'citrix_ns_id'],
            'response_patterns': ['Citrix', 'NetScaler'],
        },
    }
    
    WAF_TEST_PAYLOADS = [
        "' OR '1'='1",
        "../../etc/passwd",
        "<script>alert(1)</script>",
        "UNION SELECT",
        "1; DROP TABLE users",
    ]
    
    def __init__(
        self,
        target: str,
        config: Optional[Dict[str, Any]] = None
    ):
        """
        Initialize the WAF detector.
        
        Args:
            target: Target URL
            config: Configuration dictionary
        """
        self.target = target.rstrip('/')
        self.config = config or {}
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        })
        
        self.timeout = self.config.get('timeout', 15)
        self.verify_ssl = self.config.get('verify_ssl', False)
        
        self.detected_wafs: List[str] = []
        self.errors: List[str] = []
    
    def _safe_get_headers(self, response: Optional[requests.Response]) -> Dict[str, str]:
        """Safely get headers from response with fallback."""
        if response and hasattr(response, 'headers'):
            return dict(response.headers)
        return {}
    
    def _safe_get_cookies(self, response: Optional[requests.Response]) -> Dict[str, str]:
        """Safely get cookies from response with fallback."""
        cookies = {}
        if response and hasattr(response, 'cookies'):
            for cookie in response.cookies:
                cookies[cookie.name] = cookie.value
        return cookies
    
    def _safe_get_text(self, response: Optional[requests.Response]) -> str:
        """Safely get response text with fallback."""
        if response and hasattr(response, 'text'):
            return response.text or ''
        return ''
    
    def _is_valid_response(self, response: Optional[requests.Response]) -> bool:
        """Check if response is valid for analysis."""
        if response is None:
            return False
        if not hasattr(response, 'status_code'):
            return False
        return True
    
    def _check_response_status(self, response: Optional[requests.Response]) -> bool:
        """Check if response status is acceptable."""
        if not self._is_valid_response(response):
            return False
        # Consider 200-399 as acceptable for WAF detection
        return 200 <= response.status_code < 400
    
    def _validate_baseline(self, result: Tuple) -> Tuple[bool, Dict[str, Any]]:
        """
        Validate baseline fetch result.
        
        Returns:
            Tuple of (success, data_dict)
        """
        headers, text, cookies = result
        
        # Check if any data was received
        if headers is None and text is None and cookies is None:
            return False, {
                'headers': {},
                'text': '',
                'cookies': {},
                'error': 'Baseline fetch failed completely'
            }
        
        return True, {
            'headers': headers or {},
            'text': text or '',
            'cookies': cookies or {},
        }
    
    def fetch_baseline(self) -> Tuple[Optional[Dict[str, str]], Optional[str], Optional[Dict[str, str]]]:
        """
        Fetch baseline response for comparison.
        
        Returns:
            Tuple of (headers, text, cookies)
        """
        try:
            response = self.session.get(
                self.target,
                timeout=self.timeout,
                verify=self.verify_ssl
            )
            
            headers = self._safe_get_headers(response)
            text = self._safe_get_text(response)
            cookies = self._safe_get_cookies(response)
            
            # Even if status is not 200, we might still have useful data
            if response.status_code >= 400:
                self.errors.append(f"Baseline returned status: {response.status_code}")
            
            return headers, text, cookies
            
        except Timeout as e:
            self.errors.append(f"Baseline fetch timed out: {str(e)}")
            return None, None, None
        except ConnectionError as e:
            self.errors.append(f"Connection error: {str(e)}")
            return None, None, None
        except RequestException as e:
            self.errors.append(f"Baseline fetch failed: {str(e)}")
            return None, None, None
    
    def test_payload(self, payload: str) -> Optional[requests.Response]:
        """
        Send a test payload to check WAF response.
        
        Args:
            payload: Test payload string
            
        Returns:
            HTTP response or None
        """
        try:
            params = {'test': payload, 'q': payload, 'search': payload}
            response = self.session.get(
                self.target,
                params=params,
                timeout=self.timeout,
                verify=self.verify_ssl
            )
            return response
            
        except RequestException:
            return None
    
    def detect_from_signatures(
        self,
        headers: Dict[str, str],
        text: str,
        cookies: Dict[str, str]
    ) -> List[str]:
        """
        Detect WAF from response signatures.
        
        Args:
            headers: Response headers
            text: Response text
            cookies: Response cookies
            
        Returns:
            List of detected WAF names
        """
        detected = []
        
        # Guard against empty data
        if not headers and not text and not cookies:
            return detected
        
        for waf_name, signatures in self.WAF_SIGNATURES.items():
            is_detected = False
            
            # Check headers
            if headers:
                for header in signatures.get('headers', []):
                    if header.lower() in [h.lower() for h in headers]:
                        is_detected = True
                        break
            
            # Check cookies
            if not is_detected and cookies:
                for cookie in signatures.get('cookies', []):
                    if cookie.lower() in [c.lower() for c in cookies]:
                        is_detected = True
                        break
            
            # Check response patterns
            if not is_detected and text:
                for pattern in signatures.get('response_patterns', []):
                    if pattern.lower() in text.lower():
                        is_detected = True
                        break
            
            if is_detected:
                detected.append(waf_name)
        
        return detected
    
    def detect_from_behavior(self) -> List[str]:
        """
        Detect WAF from behavioral analysis with payloads.
        
        Returns:
            List of detected WAF names
        """
        for payload in self.WAF_TEST_PAYLOADS:
            response = self.test_payload(payload)
            
            if self._is_valid_response(response):
                if response.status_code in [403, 406, 501]:
                    headers = self._safe_get_headers(response)
                    text = self._safe_get_text(response)
                    cookies = self._safe_get_cookies(response)
                    
                    behavioral_wafs = self.detect_from_signatures(headers, text, cookies)
                    
                    if behavioral_wafs:
                        return behavioral_wafs
        
        return []
    
    def _detect_from_headers_only(self, headers: Dict[str, str]) -> List[str]:
        """
        Detect WAF from headers only (when no text/cookies available).
        
        Args:
            headers: Response headers
            
        Returns:
            List of detected WAF names
        """
        detected = []
        
        for waf_name, signatures in self.WAF_SIGNATURES.items():
            for header in signatures.get('headers', []):
                if header.lower() in [h.lower() for h in headers]:
                    detected.append(waf_name)
                    break
        
        return detected
    
    def run(self) -> Dict[str, Any]:
        """
        Run WAF detection.
        
        Returns:
            Dictionary with detection results
        """
        headers, text, cookies = self.fetch_baseline()
        
        # Validate baseline
        success, data = self._validate_baseline((headers, text, cookies))
        
        if not success:
            return {
                'findings': [],
                'errors': self.errors,
                'waf_detected': [],
                'has_waf': False,
                'detection_status': 'failed',
                'error': data.get('error', 'Unknown error'),
            }
        
        # Try to detect from available data
        signature_wafs = []
        behavioral_wafs = []
        
        # Always try signature detection if we have any data
        if data.get('headers') or data.get('text') or data.get('cookies'):
            signature_wafs = self.detect_from_signatures(
                data.get('headers', {}),
                data.get('text', ''),
                data.get('cookies', {})
            )
        
        # If we have text, try behavioral detection
        if data.get('text'):
            behavioral_wafs = self.detect_from_behavior()
        
        # If no data at all, try headers-only detection
        if not signature_wafs and not behavioral_wafs and data.get('headers'):
            signature_wafs = self._detect_from_headers_only(data.get('headers', {}))
        
        all_wafs = list(set(signature_wafs + behavioral_wafs))
        
        findings = []
        
        if all_wafs:
            findings.append({
                'type': 'WAF Detected',
                'severity': 'info',
                'target': self.target,
                'description': f'Web Application Firewall detected: {", ".join(all_wafs)}',
                'evidence': {
                    'detected_wafs': all_wafs,
                    'detection_method': 'signature' if signature_wafs else 'behavioral',
                    'has_text_response': bool(data.get('text')),
                    'has_headers': bool(data.get('headers')),
                },
                'remediation': 'Review WAF configuration. Consider WAF bypass testing.',
            })
        else:
            # Check if we had enough data to make a determination
            if data.get('text') or data.get('headers'):
                findings.append({
                    'type': 'No WAF Detected',
                    'severity': 'info',
                    'target': self.target,
                    'description': 'No Web Application Firewall detected',
                    'evidence': {
                        'has_text_response': bool(data.get('text')),
                        'has_headers': bool(data.get('headers')),
                    },
                    'remediation': 'Consider implementing a WAF for additional protection',
                })
            else:
                findings.append({
                    'type': 'WAF Detection Inconclusive',
                    'severity': 'info',
                    'target': self.target,
                    'description': 'Insufficient data to determine WAF presence',
                    'remediation': 'Manual review required',
                })
        
        return {
            'findings': findings,
            'errors': self.errors,
            'target': self.target,
            'waf_detected': all_wafs,
            'has_waf': len(all_wafs) > 0,
            'detection_status': 'success' if (data.get('text') or data.get('headers')) else 'partial',
            'data_available': {
                'headers': bool(data.get('headers')),
                'text': bool(data.get('text')),
                'cookies': bool(data.get('cookies')),
            },
        }
